/**
 * Playwright tests for the SAT Math interactive widgets.
 *
 * Each test loads a static HTML fixture from `fixtures/` (generated by
 * `python -m scripts.sat_rework.generate_fixtures`) and exercises the
 * widget the same way a student would: clicks buttons, drags points,
 * moves sliders. We assert that user-visible state (text content,
 * dataset attributes) updates correctly.
 *
 * Why fixtures, not the live LMS:
 * - No login required
 * - No iframe sandbox to fight (the fixture IS the iframe content,
 *   running in the top-level frame so Playwright can interact with
 *   buttons directly)
 * - Tests run in <5s and catch widget-logic bugs that the manual
 *   "click and pray" approach inside the LMS misses
 *
 * Run locally:
 *   cd frontend
 *   npx playwright test widget-tests/widgets.spec.ts
 *
 * The fixtures are loaded via the `file://` protocol so no server
 * needs to be running.
 */
import { test, expect } from "@playwright/test";

// Resolve a fixture filename to a file:// URL relative to this spec.
// Playwright spawns its own process so process.cwd() points at the
// frontend dir; we know fixtures live under widget-tests/fixtures/.
const FIX = (slug: string) =>
  "file:///" +
  process.cwd().replace(/\\/g, "/") +
  "/widget-tests/fixtures/" +
  slug +
  ".html";

// ---------------------------------------------------------------------------
// Lesson 1 — Equation Solver Workbench
// ---------------------------------------------------------------------------
test.describe("Lesson 1: Equation Solver Workbench", () => {
  test("solves all 4 problems via per-problem buttons", async ({ page }) => {
    await page.goto(FIX("lesson-01-solving-linear"));

    // ---- Problem 0: 3x + 7 = 22 → −7, ÷3 → x = 5 ----
    await expect(page.locator("#eqL")).toHaveText("3x + 7");
    await expect(page.locator("#eqR")).toHaveText("22");
    await page.click('#ops button[data-op="-7"]');
    await expect(page.locator("#eqL")).toHaveText("3x");
    await expect(page.locator("#eqR")).toHaveText("15");
    await page.click('#ops button[data-op="/3"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("5");
    await expect(page.locator("#explain")).toContainText("Solved");
    await expect(page.locator("#explain")).toContainText("x = 5");

    // ---- Problem 1: 5x − 4 = 16 → +4, ÷5 → x = 4 ----
    await page.click('.problem-picker button[data-prob="1"]');
    await expect(page.locator("#eqL")).toHaveText("5x - 4");
    await expect(page.locator("#eqR")).toHaveText("16");
    await page.click('#ops button[data-op="+4"]');
    await expect(page.locator("#eqL")).toHaveText("5x");
    await expect(page.locator("#eqR")).toHaveText("20");
    await page.click('#ops button[data-op="/5"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("4");
    await expect(page.locator("#explain")).toContainText("x = 4");

    // ---- Problem 2: 2(x+3) = 14 → distribute, −6, ÷2 → x = 4 ----
    await page.click('.problem-picker button[data-prob="2"]');
    await expect(page.locator("#eqL")).toHaveText("2(x + 3)");
    await expect(page.locator("#eqR")).toHaveText("14");
    await page.click('#ops button[data-op="distribute"]');
    await expect(page.locator("#eqL")).toHaveText("2x + 6");
    await expect(page.locator("#eqR")).toHaveText("14");
    await page.click('#ops button[data-op="-6"]');
    await expect(page.locator("#eqL")).toHaveText("2x");
    await expect(page.locator("#eqR")).toHaveText("8");
    await page.click('#ops button[data-op="/2"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("4");

    // ---- Problem 3: 4x + 9 = 2x + 17 → −2x, −9, ÷2 → x = 4 ----
    await page.click('.problem-picker button[data-prob="3"]');
    await expect(page.locator("#eqL")).toHaveText("4x + 9");
    await expect(page.locator("#eqR")).toHaveText("2x + 17");
    await page.click('#ops button[data-op="-2x"]');
    await expect(page.locator("#eqL")).toHaveText("2x + 9");
    await expect(page.locator("#eqR")).toHaveText("17");
    await page.click('#ops button[data-op="-9"]');
    await expect(page.locator("#eqL")).toHaveText("2x");
    await expect(page.locator("#eqR")).toHaveText("8");
    await page.click('#ops button[data-op="/2"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("4");
  });

  test("rejects premature divide and explains why", async ({ page }) => {
    await page.goto(FIX("lesson-01-solving-linear"));
    // Try to divide before subtracting the constant
    await page.click('#ops button[data-op="/3"]');
    // Equation should NOT have changed
    await expect(page.locator("#eqL")).toHaveText("3x + 7");
    await expect(page.locator("#eqR")).toHaveText("22");
    // Explain should warn about the constant
    await expect(page.locator("#explain")).toContainText(/constant on the left/i);
  });

  test("reset returns to the original equation", async ({ page }) => {
    await page.goto(FIX("lesson-01-solving-linear"));
    await page.click('#ops button[data-op="-7"]');
    await expect(page.locator("#eqR")).toHaveText("15");
    await page.click("#resetBtn");
    await expect(page.locator("#eqL")).toHaveText("3x + 7");
    await expect(page.locator("#eqR")).toHaveText("22");
  });
});

// ---------------------------------------------------------------------------
// Lesson 2 — Inequality Flipper
// ---------------------------------------------------------------------------
test.describe("Lesson 2: Inequality Flipper", () => {
  test("walks through the 2-step flip example", async ({ page }) => {
    await page.goto(FIX("lesson-02-inequalities"));
    // Initial state
    await expect(page.locator("#eq")).toHaveText("−2x + 3 < 9");
    await expect(page.locator("#flipWarn")).not.toHaveClass(/on/);

    // Step 1: −3 both sides → −2x < 6 (no flip warning)
    await page.click("#step1");
    await expect(page.locator("#eq")).toHaveText("−2x < 6");
    await expect(page.locator("#flipWarn")).not.toHaveClass(/on/);

    // Step 2: ÷(−2) and flip → x > −3 (warning visible)
    await page.click("#step2");
    await expect(page.locator("#eq")).toHaveText("x > −3");
    await expect(page.locator("#flipWarn")).toHaveClass(/on/);

    // Reset
    await page.click("#reset");
    await expect(page.locator("#eq")).toHaveText("−2x + 3 < 9");
    await expect(page.locator("#flipWarn")).not.toHaveClass(/on/);
  });
});

// ---------------------------------------------------------------------------
// Lesson 3 — Two-Line Intersection Explorer
// ---------------------------------------------------------------------------
test.describe("Lesson 3: Two-Line Intersection Explorer", () => {
  test("computes the intersection of two lines", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    // Default: 2x + y = 7  AND  x − y = −1  → x = 2, y = 3
    await expect(page.locator("#info")).toContainText("x = 2");
    await expect(page.locator("#info")).toContainText("y = 3");
  });

  test("detects parallel (no solution)", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    // Set both lines to same slope, different intercepts:
    //   2x + y = 7  ;  4x + 2y = 0   (slope -2 each, intercepts 7 vs 0 — not parallel actually since 4x+2y=0 → y=-2x same slope, intercept 0 vs 7 → parallel)
    await page.fill("#a2", "4");
    await page.fill("#b2", "2");
    await page.fill("#c2", "0");
    await expect(page.locator("#info")).toContainText(/no solution/i);
  });

  test("detects infinite solutions when equations describe the same line", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    // Make eq2 a multiple of eq1: 2(2x + y = 7) = 4x + 2y = 14
    await page.fill("#a2", "4");
    await page.fill("#b2", "2");
    await page.fill("#c2", "14");
    await expect(page.locator("#info")).toContainText(/infinite/i);
  });

  test("equation labels follow the inputs", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    await page.fill("#a1", "3");
    await expect(page.locator("#eq1")).toContainText("3x");
  });
});

// ---------------------------------------------------------------------------
// Lesson 4 — Slope from Two Points
// ---------------------------------------------------------------------------
test.describe("Lesson 4: Slope from Two Points", () => {
  test("starts with the documented default points and slope 1", async ({ page }) => {
    await page.goto(FIX("lesson-04-slope"));
    await expect(page.locator("#p1Lbl")).toHaveText("P₁ (1, 2)");
    await expect(page.locator("#p2Lbl")).toHaveText("P₂ (5, 6)");
    await expect(page.locator("#slope")).toContainText("= 1");
  });

  test("dragging a point updates the slope formula", async ({ page }) => {
    await page.goto(FIX("lesson-04-slope"));
    // Drag p2 from (5, 6) → (3, 4). The widget clamps y to [-5, 5]
    // so we stay inside the grid. m = (4 - 2)/(3 - 1) = 2/2 = 1.
    // Wait — that's the same as the default. Let's use (4, -2) instead:
    // m = (-2 - 2)/(4 - 1) = -4/3 ≈ -1.333.
    await page.evaluate(() => {
      const canvas = document.getElementById("plane") as HTMLCanvasElement;
      const rect = canvas.getBoundingClientRect();
      // gs(x, y) → {W/2 + x*30, H/2 - y*30}, W=440, H=340
      const startX = rect.left + (440 / 2 + 5 * 30);
      const startY = rect.top + (340 / 2 - 6 * 30);
      const endX = rect.left + (440 / 2 + 4 * 30);
      const endY = rect.top + (340 / 2 - -2 * 30);
      function dispatch(type: string, x: number, y: number) {
        canvas.dispatchEvent(
          new PointerEvent(type, {
            clientX: x,
            clientY: y,
            pointerId: 1,
            bubbles: true,
            isPrimary: true,
          })
        );
      }
      dispatch("pointerdown", startX, startY);
      dispatch("pointermove", endX, endY);
      dispatch("pointerup", endX, endY);
    });
    await expect(page.locator("#p2Lbl")).toHaveText("P₂ (4, -2)");
    // m = (-2 - 2)/(4 - 1) = -4/3 → "-1.333"
    await expect(page.locator("#slope")).toContainText("-1.333");
  });

  test("vertical line shows undefined slope", async ({ page }) => {
    await page.goto(FIX("lesson-04-slope"));
    // Drag p2 onto same x as p1 (1, ?). Use coordinate (1, 5).
    await page.evaluate(() => {
      const canvas = document.getElementById("plane") as HTMLCanvasElement;
      const rect = canvas.getBoundingClientRect();
      const startX = rect.left + (440 / 2 + 5 * 30);
      const startY = rect.top + (340 / 2 - 6 * 30);
      const endX = rect.left + (440 / 2 + 1 * 30);
      const endY = rect.top + (340 / 2 - 5 * 30);
      function dispatch(type: string, x: number, y: number) {
        canvas.dispatchEvent(
          new PointerEvent(type, {
            clientX: x,
            clientY: y,
            pointerId: 1,
            bubbles: true,
            isPrimary: true,
          })
        );
      }
      dispatch("pointerdown", startX, startY);
      dispatch("pointermove", endX, endY);
      dispatch("pointerup", endX, endY);
    });
    await expect(page.locator("#slope")).toContainText(/undefined/i);
  });
});

// ---------------------------------------------------------------------------
// Lesson 5 — y = mx + b Explorer
// ---------------------------------------------------------------------------
test.describe("Lesson 5: y = mx + b Explorer", () => {
  test("default state shows y = 1·x + 0 (rendered as y = x)", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await expect(page.locator("#eq")).toHaveText("y = x");
    await expect(page.locator("#mVal")).toHaveText("1");
    await expect(page.locator("#bVal")).toHaveText("0");
  });

  test("changing m updates the equation", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await page.evaluate(() => {
      const m = document.getElementById("m") as HTMLInputElement;
      m.value = "2";
      m.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toHaveText("y = 2·x");
    await expect(page.locator("#mVal")).toHaveText("2");
  });

  test("changing b updates the equation", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await page.evaluate(() => {
      const b = document.getElementById("b") as HTMLInputElement;
      b.value = "3";
      b.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toHaveText("y = x + 3");
  });

  test("negative m + negative b shows minus signs correctly", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await page.evaluate(() => {
      const m = document.getElementById("m") as HTMLInputElement;
      const b = document.getElementById("b") as HTMLInputElement;
      m.value = "-2";
      m.dispatchEvent(new Event("input", { bubbles: true }));
      b.value = "-4";
      b.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toHaveText("y = -2·x − 4");
  });
});

// ---------------------------------------------------------------------------
// Lesson 6 — Real-World Linear Model Translator
// ---------------------------------------------------------------------------
test.describe("Lesson 6: Real-World Linear Model Translator", () => {
  test("default scenario is the phone bill", async ({ page }) => {
    await page.goto(FIX("lesson-06-interpreting"));
    await expect(page.locator("#eq")).toContainText("C = 0.10·m + 25");
    await expect(page.locator("#slopePart")).toContainText("text message");
    await expect(page.locator("#interPart")).toContainText("base fee");
  });

  test("clicking a different scenario swaps the equation, slope, intercept, and story", async ({
    page,
  }) => {
    await page.goto(FIX("lesson-06-interpreting"));
    // Click "road trip"
    await page.click('.scenario-picker button[data-s="1"]');
    await expect(page.locator("#eq")).toContainText("D = 60·t + 30");
    await expect(page.locator("#slopePart")).toContainText("60 mph");
    await expect(page.locator("#interPart")).toContainText("head start");
    await expect(page.locator("#storyInfo")).toContainText("60 mph");

    // Click "plant growth"
    await page.click('.scenario-picker button[data-s="2"]');
    await expect(page.locator("#eq")).toContainText("H = 0.5·d + 4");
    await expect(page.locator("#slopePart")).toContainText("0.5 cm");
    await expect(page.locator("#interPart")).toContainText("seedling");

    // Click "savings"
    await page.click('.scenario-picker button[data-s="3"]');
    await expect(page.locator("#eq")).toContainText("B = 50·w + 200");
  });

  test("active scenario button gets the .active class", async ({ page }) => {
    await page.goto(FIX("lesson-06-interpreting"));
    await page.click('.scenario-picker button[data-s="2"]');
    await expect(page.locator('.scenario-picker button[data-s="2"]')).toHaveClass(/active/);
    await expect(page.locator('.scenario-picker button[data-s="0"]')).not.toHaveClass(/active/);
  });
});

// ---------------------------------------------------------------------------
// Lesson 7 — Proportion Solver
// ---------------------------------------------------------------------------
test.describe("Lesson 7: Proportion Solver", () => {
  test("solves a/b = c/d when one box is blank", async ({ page }) => {
    await page.goto(FIX("lesson-07-ratios"));
    // Default 3/5 = 12/?  → d = (5*12)/3 = 20
    await page.click("#solveBtn");
    await expect(page.locator("#ans")).toContainText("20");
    await expect(page.locator("#d")).toHaveValue("20");
  });

  test("rejects when not exactly one box is blank", async ({ page }) => {
    await page.goto(FIX("lesson-07-ratios"));
    await page.fill("#d", "15");
    await page.click("#solveBtn");
    await expect(page.locator("#ans")).toContainText(/EXACTLY one/i);
  });
});

// ---------------------------------------------------------------------------
// Lesson 8 — Percent Calculator
// ---------------------------------------------------------------------------
test.describe("Lesson 8: Percent Calculator", () => {
  test("default mode: 20% of 80 = 16", async ({ page }) => {
    await page.goto(FIX("lesson-08-percentages"));
    await expect(page.locator("#result")).toContainText("16");
  });

  test("switching to mode 1 computes A as % of B", async ({ page }) => {
    await page.goto(FIX("lesson-08-percentages"));
    await page.click('.mode-picker button[data-mode="1"]');
    // After switch: A=16, B=80 → 16 is 20% of 80
    await expect(page.locator("#result")).toContainText("20%");
  });

  test("switching to mode 2 computes A as X% of what", async ({ page }) => {
    await page.goto(FIX("lesson-08-percentages"));
    await page.click('.mode-picker button[data-mode="2"]');
    // After switch: X=20%, A=16 → 16 is 20% of 80
    await expect(page.locator("#result")).toContainText("80");
  });
});

// ---------------------------------------------------------------------------
// Lesson 9 — Live Statistics Calculator
// ---------------------------------------------------------------------------
test.describe("Lesson 9: Live Statistics", () => {
  test("preset gives mean=7.6, median=7, mode=7", async ({ page }) => {
    await page.goto(FIX("lesson-09-statistics"));
    await page.click("#presetBtn");
    await expect(page.locator("#mean")).toHaveText("7.6");
    await expect(page.locator("#median")).toHaveText("7");
    await expect(page.locator("#mode")).toHaveText("7");
  });

  test("clear empties the list", async ({ page }) => {
    await page.goto(FIX("lesson-09-statistics"));
    await page.click("#presetBtn");
    await page.click("#clearBtn");
    await expect(page.locator("#mean")).toHaveText("—");
  });

  test("adding a number updates the mean", async ({ page }) => {
    await page.goto(FIX("lesson-09-statistics"));
    await page.fill("#newNum", "10");
    await page.click("#addBtn");
    await page.fill("#newNum", "20");
    await page.click("#addBtn");
    await expect(page.locator("#mean")).toHaveText("15");
  });
});

// ---------------------------------------------------------------------------
// Lesson 10 — Scatter / Line of Best Fit Tuner
// ---------------------------------------------------------------------------
test.describe("Lesson 10: Scatter / Line of Best Fit", () => {
  test("default has indigo line and point dataset", async ({ page }) => {
    await page.goto(FIX("lesson-10-scatter"));
    await expect(page.locator("#eq")).toHaveText("y = 1.0·x + 0.0");
    await expect(page.locator("#fit")).toContainText(/Sum of squared residuals/);
  });

  test("changing slope updates equation and residual", async ({ page }) => {
    await page.goto(FIX("lesson-10-scatter"));
    await page.evaluate(() => {
      const m = document.getElementById("m") as HTMLInputElement;
      m.value = "0.7"; m.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toContainText("0.7");
  });

  test("dataset picker swaps the points", async ({ page }) => {
    await page.goto(FIX("lesson-10-scatter"));
    await page.click('.dataset-picker button[data-set="1"]');
    await expect(page.locator('.dataset-picker button[data-set="1"]')).toHaveClass(/active/);
  });
});

// ---------------------------------------------------------------------------
// Lesson 11 — Two-Way Table Probability
// ---------------------------------------------------------------------------
test.describe("Lesson 11: Two-Way Table Probability", () => {
  test("default P(adult) = 50/100", async ({ page }) => {
    await page.goto(FIX("lesson-11-probability"));
    await expect(page.locator("#result")).toContainText("50 / 100");
    await expect(page.locator("#grand")).toHaveText("100");
  });

  test("switching to conditional P(likes | adult) = 40/50", async ({ page }) => {
    await page.goto(FIX("lesson-11-probability"));
    await page.click('.q-picker button[data-q="3"]');
    await expect(page.locator("#result")).toContainText("40 / 50");
    await expect(page.locator("#result")).toContainText("80%");
  });

  test("editing a cell updates the totals", async ({ page }) => {
    await page.goto(FIX("lesson-11-probability"));
    await page.fill("#aa", "60");
    await expect(page.locator("#ra")).toHaveText("70");
    await expect(page.locator("#grand")).toHaveText("120");
  });
});

// ---------------------------------------------------------------------------
// Lesson 12 — Quadratic Solver
// ---------------------------------------------------------------------------
test.describe("Lesson 12: Quadratic Solver", () => {
  test("default x² + 5x + 6 → roots -2, -3", async ({ page }) => {
    await page.goto(FIX("lesson-12-quadratics"));
    await expect(page.locator("#disc")).toContainText("2 real roots");
    await expect(page.locator("#roots")).toContainText("-2");
    await expect(page.locator("#roots")).toContainText("-3");
  });

  test("discriminant 0 → 1 repeated root", async ({ page }) => {
    await page.goto(FIX("lesson-12-quadratics"));
    // x² - 4x + 4 has discriminant = 16 - 16 = 0, root x = 2
    await page.fill("#a", "1");
    await page.fill("#b", "-4");
    await page.fill("#c", "4");
    await expect(page.locator("#disc")).toContainText("1 repeated root");
    await expect(page.locator("#roots")).toContainText("double root");
  });

  test("negative discriminant → no real roots", async ({ page }) => {
    await page.goto(FIX("lesson-12-quadratics"));
    // x² + x + 1: disc = 1 - 4 = -3
    await page.fill("#a", "1");
    await page.fill("#b", "1");
    await page.fill("#c", "1");
    await expect(page.locator("#disc")).toContainText("no real roots");
  });
});

// ---------------------------------------------------------------------------
// Lesson 13 — Parabola Explorer
// ---------------------------------------------------------------------------
test.describe("Lesson 13: Parabola Explorer", () => {
  test("default y = x², vertex at origin", async ({ page }) => {
    await page.goto(FIX("lesson-13-parabolas"));
    await expect(page.locator("#vertexInfo")).toContainText("vertex (0, 0)");
    await expect(page.locator("#axisInfo")).toContainText("x = 0");
  });

  test("changing b shifts the vertex", async ({ page }) => {
    await page.goto(FIX("lesson-13-parabolas"));
    // Set a=1, b=4, c=0 → vertex x = -4/(2·1) = -2, y = (-2)² + 4·(-2) + 0 = -4
    await page.evaluate(() => {
      const b = document.getElementById("b") as HTMLInputElement;
      b.value = "4"; b.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#vertexInfo")).toContainText("(-2, -4)");
  });
});

// ---------------------------------------------------------------------------
// Lesson 14 — Polynomial Expander
// ---------------------------------------------------------------------------
test.describe("Lesson 14: Polynomial Expander", () => {
  test("default (x+2)(x+3) = x² + 5x + 6", async ({ page }) => {
    await page.goto(FIX("lesson-14-polynomials"));
    await expect(page.locator("#result")).toContainText("x² + 5x + 6");
  });

  test("switch to (x+a)² mode", async ({ page }) => {
    await page.goto(FIX("lesson-14-polynomials"));
    await page.click('.method-picker button[data-m="1"]');
    // Default a=3 → (x+3)² = x² + 6x + 9
    await expect(page.locator("#result")).toContainText("x² + 6x + 9");
  });

  test("difference of squares mode", async ({ page }) => {
    await page.goto(FIX("lesson-14-polynomials"));
    await page.click('.method-picker button[data-m="2"]');
    // Default a=4, b=4 → (x+4)(x-4) = x² - 16
    await expect(page.locator("#result")).toContainText("x² − 16");
  });
});

// ---------------------------------------------------------------------------
// Lesson 15 — Exponential Curve Explorer
// ---------------------------------------------------------------------------
test.describe("Lesson 15: Exponential Explorer", () => {
  test("default y = 2 · 1.5ˣ is growth", async ({ page }) => {
    await page.goto(FIX("lesson-15-exponentials"));
    await expect(page.locator("#eq")).toHaveText("y = 2 · 1.5ˣ");
    await expect(page.locator("#kind")).toHaveText("growth");
  });

  test("base < 1 switches to decay", async ({ page }) => {
    await page.goto(FIX("lesson-15-exponentials"));
    await page.evaluate(() => {
      const b = document.getElementById("b") as HTMLInputElement;
      b.value = "0.5"; b.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#kind")).toHaveText("decay");
  });
});

// ---------------------------------------------------------------------------
// Lesson 16 — Function Transformer
// ---------------------------------------------------------------------------
test.describe("Lesson 16: Function Transformer", () => {
  test("default identity has h=0, k=0, a=1", async ({ page }) => {
    await page.goto(FIX("lesson-16-transformations"));
    await expect(page.locator("#eq")).toHaveText("y = 1·(x − 0)² + 0");
  });

  test("changing h updates equation", async ({ page }) => {
    await page.goto(FIX("lesson-16-transformations"));
    await page.evaluate(() => {
      const h = document.getElementById("h") as HTMLInputElement;
      h.value = "2"; h.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toContainText("(x − 2)²");
  });
});

// ---------------------------------------------------------------------------
// Lesson 17 — Shape Explorer (Geometry)
// ---------------------------------------------------------------------------
test.describe("Lesson 17: Shape Explorer", () => {
  test("default rectangle 6x4 → area 24, perimeter 20", async ({ page }) => {
    await page.goto(FIX("lesson-17-geometry"));
    await expect(page.locator("#formula")).toContainText("24");
    await expect(page.locator("#info1")).toContainText("20");
  });

  test("switching to right triangle shows hypotenuse", async ({ page }) => {
    await page.goto(FIX("lesson-17-geometry"));
    await page.click('.shape-picker button[data-s="2"]');
    // Default 6 and 4 → hypotenuse √52 ≈ 7.21
    await expect(page.locator("#info1")).toContainText("7.21");
  });
});

// ---------------------------------------------------------------------------
// Lesson 18 — Circle Calculator
// ---------------------------------------------------------------------------
test.describe("Lesson 18: Circle Calculator", () => {
  test("default radius 4 → diameter 8, circumference ≈ 25.13, area ≈ 50.27", async ({ page }) => {
    await page.goto(FIX("lesson-18-circles"));
    await expect(page.locator("#d")).toHaveText("8.0");
    await expect(page.locator("#c")).toHaveText("25.13");
    await expect(page.locator("#a")).toHaveText("50.27");
  });

  test("changing radius to 5 → C = 2π·5 ≈ 31.42", async ({ page }) => {
    await page.goto(FIX("lesson-18-circles"));
    await page.evaluate(() => {
      const r = document.getElementById("r") as HTMLInputElement;
      r.value = "5"; r.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#c")).toHaveText("31.42");
    await expect(page.locator("#a")).toHaveText("78.54");
  });
});

// ---------------------------------------------------------------------------
// Lesson 19 — Unit Circle Explorer (Trig)
// ---------------------------------------------------------------------------
test.describe("Lesson 19: Unit Circle / Trig", () => {
  test("default 30° → sin = 0.5, cos ≈ 0.866", async ({ page }) => {
    await page.goto(FIX("lesson-19-trigonometry"));
    await expect(page.locator("#sinV")).toHaveText("0.500");
    await expect(page.locator("#cosV")).toHaveText("0.866");
  });

  test("90° → sin = 1, cos = 0", async ({ page }) => {
    await page.goto(FIX("lesson-19-trigonometry"));
    await page.evaluate(() => {
      const a = document.getElementById("ang") as HTMLInputElement;
      a.value = "90"; a.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#sinV")).toHaveText("1.000");
    await expect(page.locator("#cosV")).toHaveText("0.000");
  });
});

// ---------------------------------------------------------------------------
// Lesson 20 — Complex Number Calculator
// ---------------------------------------------------------------------------
test.describe("Lesson 20: Complex Numbers", () => {
  test("default (3+2i) + (1+4i) = 4 + 6i", async ({ page }) => {
    await page.goto(FIX("lesson-20-complex"));
    await expect(page.locator("#result")).toContainText("4 + 6i");
  });

  test("multiplication: (3+2i)(1+4i) = -5 + 14i", async ({ page }) => {
    await page.goto(FIX("lesson-20-complex"));
    await page.click('.op-picker button[data-op="mul"]');
    await expect(page.locator("#result")).toContainText("−5 + 14i");
  });

  test("subtraction: (3+2i) − (1+4i) = 2 − 2i", async ({ page }) => {
    await page.goto(FIX("lesson-20-complex"));
    await page.click('.op-picker button[data-op="sub"]');
    await expect(page.locator("#result")).toContainText("2 − 2i");
  });
});

// ---------------------------------------------------------------------------
// Lesson 21 — 3D Shape Calculator (Volume & Surface Area)
// ---------------------------------------------------------------------------
test.describe("Lesson 21: 3D Shape Calculator", () => {
  test("default cube side 4 → V=64, SA=96", async ({ page }) => {
    await page.goto(FIX("lesson-21-volume"));
    await expect(page.locator("#volV")).toHaveText("64");
    await expect(page.locator("#saV")).toHaveText("96");
  });

  test("sphere mode default radius 4 → V ≈ 268.08, SA ≈ 201.06", async ({ page }) => {
    await page.goto(FIX("lesson-21-volume"));
    await page.click('.shape-picker button[data-s="3"]');
    await expect(page.locator("#volV")).toHaveText("268.08");
    await expect(page.locator("#saV")).toHaveText("201.06");
  });

  test("cylinder mode default r=4 h=3 → V ≈ 150.80", async ({ page }) => {
    await page.goto(FIX("lesson-21-volume"));
    await page.click('.shape-picker button[data-s="2"]');
    await expect(page.locator("#volV")).toHaveText("150.8");
  });
});
