/**
 * Playwright tests for the SAT Math interactive widgets.
 *
 * Each test loads a static HTML fixture from `fixtures/` (generated by
 * `python -m scripts.sat_rework.generate_fixtures`) and exercises the
 * widget the same way a student would: clicks buttons, drags points,
 * moves sliders. We assert that user-visible state (text content,
 * dataset attributes) updates correctly.
 *
 * Why fixtures, not the live LMS:
 * - No login required
 * - No iframe sandbox to fight (the fixture IS the iframe content,
 *   running in the top-level frame so Playwright can interact with
 *   buttons directly)
 * - Tests run in <5s and catch widget-logic bugs that the manual
 *   "click and pray" approach inside the LMS misses
 *
 * Run locally:
 *   cd frontend
 *   npx playwright test widget-tests/widgets.spec.ts
 *
 * The fixtures are loaded via the `file://` protocol so no server
 * needs to be running.
 */
import { test, expect } from "@playwright/test";

// Resolve a fixture filename to a file:// URL relative to this spec.
// Playwright spawns its own process so process.cwd() points at the
// frontend dir; we know fixtures live under widget-tests/fixtures/.
const FIX = (slug: string) =>
  "file:///" +
  process.cwd().replace(/\\/g, "/") +
  "/widget-tests/fixtures/" +
  slug +
  ".html";

// ---------------------------------------------------------------------------
// Lesson 1 — Equation Solver Workbench
// ---------------------------------------------------------------------------
test.describe("Lesson 1: Equation Solver Workbench", () => {
  test("solves all 4 problems via per-problem buttons", async ({ page }) => {
    await page.goto(FIX("lesson-01-solving-linear"));

    // ---- Problem 0: 3x + 7 = 22 → −7, ÷3 → x = 5 ----
    await expect(page.locator("#eqL")).toHaveText("3x + 7");
    await expect(page.locator("#eqR")).toHaveText("22");
    await page.click('#ops button[data-op="-7"]');
    await expect(page.locator("#eqL")).toHaveText("3x");
    await expect(page.locator("#eqR")).toHaveText("15");
    await page.click('#ops button[data-op="/3"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("5");
    await expect(page.locator("#explain")).toContainText("Solved");
    await expect(page.locator("#explain")).toContainText("x = 5");

    // ---- Problem 1: 5x − 4 = 16 → +4, ÷5 → x = 4 ----
    await page.click('.problem-picker button[data-prob="1"]');
    await expect(page.locator("#eqL")).toHaveText("5x - 4");
    await expect(page.locator("#eqR")).toHaveText("16");
    await page.click('#ops button[data-op="+4"]');
    await expect(page.locator("#eqL")).toHaveText("5x");
    await expect(page.locator("#eqR")).toHaveText("20");
    await page.click('#ops button[data-op="/5"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("4");
    await expect(page.locator("#explain")).toContainText("x = 4");

    // ---- Problem 2: 2(x+3) = 14 → distribute, −6, ÷2 → x = 4 ----
    await page.click('.problem-picker button[data-prob="2"]');
    await expect(page.locator("#eqL")).toHaveText("2(x + 3)");
    await expect(page.locator("#eqR")).toHaveText("14");
    await page.click('#ops button[data-op="distribute"]');
    await expect(page.locator("#eqL")).toHaveText("2x + 6");
    await expect(page.locator("#eqR")).toHaveText("14");
    await page.click('#ops button[data-op="-6"]');
    await expect(page.locator("#eqL")).toHaveText("2x");
    await expect(page.locator("#eqR")).toHaveText("8");
    await page.click('#ops button[data-op="/2"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("4");

    // ---- Problem 3: 4x + 9 = 2x + 17 → −2x, −9, ÷2 → x = 4 ----
    await page.click('.problem-picker button[data-prob="3"]');
    await expect(page.locator("#eqL")).toHaveText("4x + 9");
    await expect(page.locator("#eqR")).toHaveText("2x + 17");
    await page.click('#ops button[data-op="-2x"]');
    await expect(page.locator("#eqL")).toHaveText("2x + 9");
    await expect(page.locator("#eqR")).toHaveText("17");
    await page.click('#ops button[data-op="-9"]');
    await expect(page.locator("#eqL")).toHaveText("2x");
    await expect(page.locator("#eqR")).toHaveText("8");
    await page.click('#ops button[data-op="/2"]');
    await expect(page.locator("#eqL")).toHaveText("x");
    await expect(page.locator("#eqR")).toHaveText("4");
  });

  test("rejects premature divide and explains why", async ({ page }) => {
    await page.goto(FIX("lesson-01-solving-linear"));
    // Try to divide before subtracting the constant
    await page.click('#ops button[data-op="/3"]');
    // Equation should NOT have changed
    await expect(page.locator("#eqL")).toHaveText("3x + 7");
    await expect(page.locator("#eqR")).toHaveText("22");
    // Explain should warn about the constant
    await expect(page.locator("#explain")).toContainText(/constant on the left/i);
  });

  test("reset returns to the original equation", async ({ page }) => {
    await page.goto(FIX("lesson-01-solving-linear"));
    await page.click('#ops button[data-op="-7"]');
    await expect(page.locator("#eqR")).toHaveText("15");
    await page.click("#resetBtn");
    await expect(page.locator("#eqL")).toHaveText("3x + 7");
    await expect(page.locator("#eqR")).toHaveText("22");
  });
});

// ---------------------------------------------------------------------------
// Lesson 2 — Inequality Flipper
// ---------------------------------------------------------------------------
test.describe("Lesson 2: Inequality Flipper", () => {
  test("walks through the 2-step flip example", async ({ page }) => {
    await page.goto(FIX("lesson-02-inequalities"));
    // Initial state
    await expect(page.locator("#eq")).toHaveText("−2x + 3 < 9");
    await expect(page.locator("#flipWarn")).not.toHaveClass(/on/);

    // Step 1: −3 both sides → −2x < 6 (no flip warning)
    await page.click("#step1");
    await expect(page.locator("#eq")).toHaveText("−2x < 6");
    await expect(page.locator("#flipWarn")).not.toHaveClass(/on/);

    // Step 2: ÷(−2) and flip → x > −3 (warning visible)
    await page.click("#step2");
    await expect(page.locator("#eq")).toHaveText("x > −3");
    await expect(page.locator("#flipWarn")).toHaveClass(/on/);

    // Reset
    await page.click("#reset");
    await expect(page.locator("#eq")).toHaveText("−2x + 3 < 9");
    await expect(page.locator("#flipWarn")).not.toHaveClass(/on/);
  });
});

// ---------------------------------------------------------------------------
// Lesson 3 — Two-Line Intersection Explorer
// ---------------------------------------------------------------------------
test.describe("Lesson 3: Two-Line Intersection Explorer", () => {
  test("computes the intersection of two lines", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    // Default: 2x + y = 7  AND  x − y = −1  → x = 2, y = 3
    await expect(page.locator("#info")).toContainText("x = 2");
    await expect(page.locator("#info")).toContainText("y = 3");
  });

  test("detects parallel (no solution)", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    // Set both lines to same slope, different intercepts:
    //   2x + y = 7  ;  4x + 2y = 0   (slope -2 each, intercepts 7 vs 0 — not parallel actually since 4x+2y=0 → y=-2x same slope, intercept 0 vs 7 → parallel)
    await page.fill("#a2", "4");
    await page.fill("#b2", "2");
    await page.fill("#c2", "0");
    await expect(page.locator("#info")).toContainText(/no solution/i);
  });

  test("detects infinite solutions when equations describe the same line", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    // Make eq2 a multiple of eq1: 2(2x + y = 7) = 4x + 2y = 14
    await page.fill("#a2", "4");
    await page.fill("#b2", "2");
    await page.fill("#c2", "14");
    await expect(page.locator("#info")).toContainText(/infinite/i);
  });

  test("equation labels follow the inputs", async ({ page }) => {
    await page.goto(FIX("lesson-03-systems"));
    await page.fill("#a1", "3");
    await expect(page.locator("#eq1")).toContainText("3x");
  });
});

// ---------------------------------------------------------------------------
// Lesson 4 — Slope from Two Points
// ---------------------------------------------------------------------------
test.describe("Lesson 4: Slope from Two Points", () => {
  test("starts with the documented default points and slope 1", async ({ page }) => {
    await page.goto(FIX("lesson-04-slope"));
    await expect(page.locator("#p1Lbl")).toHaveText("P₁ (1, 2)");
    await expect(page.locator("#p2Lbl")).toHaveText("P₂ (5, 6)");
    await expect(page.locator("#slope")).toContainText("= 1");
  });

  test("dragging a point updates the slope formula", async ({ page }) => {
    await page.goto(FIX("lesson-04-slope"));
    // Drag p2 from (5, 6) → (3, 4). The widget clamps y to [-5, 5]
    // so we stay inside the grid. m = (4 - 2)/(3 - 1) = 2/2 = 1.
    // Wait — that's the same as the default. Let's use (4, -2) instead:
    // m = (-2 - 2)/(4 - 1) = -4/3 ≈ -1.333.
    await page.evaluate(() => {
      const canvas = document.getElementById("plane") as HTMLCanvasElement;
      const rect = canvas.getBoundingClientRect();
      // gs(x, y) → {W/2 + x*30, H/2 - y*30}, W=440, H=340
      const startX = rect.left + (440 / 2 + 5 * 30);
      const startY = rect.top + (340 / 2 - 6 * 30);
      const endX = rect.left + (440 / 2 + 4 * 30);
      const endY = rect.top + (340 / 2 - -2 * 30);
      function dispatch(type: string, x: number, y: number) {
        canvas.dispatchEvent(
          new PointerEvent(type, {
            clientX: x,
            clientY: y,
            pointerId: 1,
            bubbles: true,
            isPrimary: true,
          })
        );
      }
      dispatch("pointerdown", startX, startY);
      dispatch("pointermove", endX, endY);
      dispatch("pointerup", endX, endY);
    });
    await expect(page.locator("#p2Lbl")).toHaveText("P₂ (4, -2)");
    // m = (-2 - 2)/(4 - 1) = -4/3 → "-1.333"
    await expect(page.locator("#slope")).toContainText("-1.333");
  });

  test("vertical line shows undefined slope", async ({ page }) => {
    await page.goto(FIX("lesson-04-slope"));
    // Drag p2 onto same x as p1 (1, ?). Use coordinate (1, 5).
    await page.evaluate(() => {
      const canvas = document.getElementById("plane") as HTMLCanvasElement;
      const rect = canvas.getBoundingClientRect();
      const startX = rect.left + (440 / 2 + 5 * 30);
      const startY = rect.top + (340 / 2 - 6 * 30);
      const endX = rect.left + (440 / 2 + 1 * 30);
      const endY = rect.top + (340 / 2 - 5 * 30);
      function dispatch(type: string, x: number, y: number) {
        canvas.dispatchEvent(
          new PointerEvent(type, {
            clientX: x,
            clientY: y,
            pointerId: 1,
            bubbles: true,
            isPrimary: true,
          })
        );
      }
      dispatch("pointerdown", startX, startY);
      dispatch("pointermove", endX, endY);
      dispatch("pointerup", endX, endY);
    });
    await expect(page.locator("#slope")).toContainText(/undefined/i);
  });
});

// ---------------------------------------------------------------------------
// Lesson 5 — y = mx + b Explorer
// ---------------------------------------------------------------------------
test.describe("Lesson 5: y = mx + b Explorer", () => {
  test("default state shows y = 1·x + 0 (rendered as y = x)", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await expect(page.locator("#eq")).toHaveText("y = x");
    await expect(page.locator("#mVal")).toHaveText("1");
    await expect(page.locator("#bVal")).toHaveText("0");
  });

  test("changing m updates the equation", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await page.evaluate(() => {
      const m = document.getElementById("m") as HTMLInputElement;
      m.value = "2";
      m.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toHaveText("y = 2·x");
    await expect(page.locator("#mVal")).toHaveText("2");
  });

  test("changing b updates the equation", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await page.evaluate(() => {
      const b = document.getElementById("b") as HTMLInputElement;
      b.value = "3";
      b.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toHaveText("y = x + 3");
  });

  test("negative m + negative b shows minus signs correctly", async ({ page }) => {
    await page.goto(FIX("lesson-05-graphing"));
    await page.evaluate(() => {
      const m = document.getElementById("m") as HTMLInputElement;
      const b = document.getElementById("b") as HTMLInputElement;
      m.value = "-2";
      m.dispatchEvent(new Event("input", { bubbles: true }));
      b.value = "-4";
      b.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await expect(page.locator("#eq")).toHaveText("y = -2·x − 4");
  });
});

// ---------------------------------------------------------------------------
// Lesson 6 — Real-World Linear Model Translator
// ---------------------------------------------------------------------------
test.describe("Lesson 6: Real-World Linear Model Translator", () => {
  test("default scenario is the phone bill", async ({ page }) => {
    await page.goto(FIX("lesson-06-interpreting"));
    await expect(page.locator("#eq")).toContainText("C = 0.10·m + 25");
    await expect(page.locator("#slopePart")).toContainText("text message");
    await expect(page.locator("#interPart")).toContainText("base fee");
  });

  test("clicking a different scenario swaps the equation, slope, intercept, and story", async ({
    page,
  }) => {
    await page.goto(FIX("lesson-06-interpreting"));
    // Click "road trip"
    await page.click('.scenario-picker button[data-s="1"]');
    await expect(page.locator("#eq")).toContainText("D = 60·t + 30");
    await expect(page.locator("#slopePart")).toContainText("60 mph");
    await expect(page.locator("#interPart")).toContainText("head start");
    await expect(page.locator("#storyInfo")).toContainText("60 mph");

    // Click "plant growth"
    await page.click('.scenario-picker button[data-s="2"]');
    await expect(page.locator("#eq")).toContainText("H = 0.5·d + 4");
    await expect(page.locator("#slopePart")).toContainText("0.5 cm");
    await expect(page.locator("#interPart")).toContainText("seedling");

    // Click "savings"
    await page.click('.scenario-picker button[data-s="3"]');
    await expect(page.locator("#eq")).toContainText("B = 50·w + 200");
  });

  test("active scenario button gets the .active class", async ({ page }) => {
    await page.goto(FIX("lesson-06-interpreting"));
    await page.click('.scenario-picker button[data-s="2"]');
    await expect(page.locator('.scenario-picker button[data-s="2"]')).toHaveClass(/active/);
    await expect(page.locator('.scenario-picker button[data-s="0"]')).not.toHaveClass(/active/);
  });
});
